package com.tinytinybites.lifesum.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "SERVING_CATEGORY".
 */
public class ServingCategory implements java.io.Serializable {

    private Long oid;
    private Integer usemedian;
    private Integer linearsize;
    private Long lastupdated;
    private Long created;
    private String name;
    private Integer defaultsize;
    private String source;

    public ServingCategory() {
    }

    public ServingCategory(Long oid) {
        this.oid = oid;
    }

    public ServingCategory(Long oid, Integer usemedian, Integer linearsize, Long lastupdated, Long created, String name, Integer defaultsize, String source) {
        this.oid = oid;
        this.usemedian = usemedian;
        this.linearsize = linearsize;
        this.lastupdated = lastupdated;
        this.created = created;
        this.name = name;
        this.defaultsize = defaultsize;
        this.source = source;
    }

    public Long getOid() {
        return oid;
    }

    public void setOid(Long oid) {
        this.oid = oid;
    }

    public Integer getUsemedian() {
        return usemedian;
    }

    public void setUsemedian(Integer usemedian) {
        this.usemedian = usemedian;
    }

    public Integer getLinearsize() {
        return linearsize;
    }

    public void setLinearsize(Integer linearsize) {
        this.linearsize = linearsize;
    }

    public Long getLastupdated() {
        return lastupdated;
    }

    public void setLastupdated(Long lastupdated) {
        this.lastupdated = lastupdated;
    }

    public Long getCreated() {
        return created;
    }

    public void setCreated(Long created) {
        this.created = created;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getDefaultsize() {
        return defaultsize;
    }

    public void setDefaultsize(Integer defaultsize) {
        this.defaultsize = defaultsize;
    }

    public String getSource() {
        return source;
    }

    public void setSource(String source) {
        this.source = source;
    }

}
